name: Secrets Scanner

# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  lint:
    # Name the Job
    name: Scan git repo secrets
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: trufflehog-actions-scan
      uses: edplato/trufflehog-actions-scan@master
      with:
        scanArguments: "--regex --entropy=False --max_depth=50 --rules /.github/workflows/regexes.json" # Add custom options here*
